### ISSUE TITLE
quoting when building commands

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/run#11]
Right now quoting must be done manually with `run.Cmd`, e.g. https://sourcegraph.com/github.com/sourcegraph/run@main/-/blob/exit_code_test.go?L13:35

Maybe this is okay, maybe we want something a bit more succint? We could also perhaps alias `shell.Quote` so one can use `run.Quote` instead

**Comment by bobheadxi** [comment]
cc @michaellzc since this is relevant to the usage you raised here: https://github.com/sourcegraph/run/issues/4#issuecomment-1124549272 , in the linked code you do the manual quoting with backticks:

```
    cmd := fmt.Sprintf(`"..."`, c.Prefix, c.Customer)
    result, err := run.Cmd(ctx, "bash", "-c", cmd).Run().Lines()
```

**Comment by michaellzc** [comment]
let's say we do auto-quote for users (I would definitely appreciate it cuz less work for me lol), is there any unexpected side effect? 

I wonder how other open source libraries (e.g. wrappers for child_process, subprocess, etc) handle it

**Comment by bobheadxi** [comment]
For the `bash -c` case there is now `run.Bash` which does quote the entire input: https://sourcegraph.com/github.com/sourcegraph/run/-/blob/command.go?L40

**Comment by michaellzc** [comment]
nice, I think the `run.Bash` abstraction should be more than enough to cover this use case, and auto quoting sounds like a bad idea
