### ISSUE TITLE
input/output cannot handle very large content

### ISSUE THREAD

**Issue by michaellzc** [sourcegraph/run#18]
the example contains sensitive-ish information, hence it's in a private repo

https://github.com/sourcegraph/devops-gist/tree/main/michaellzc/2022-05-13-01

**Comment by bobheadxi** [comment]
Ah, I think this has to do with the default size of `bytes.Buffer`

**Comment by bobheadxi** [comment]
Definitely a buffer size issue I think, this hangs:

```go
	println("hello")
	var file bytes.Buffer
	err := run.Cmd(ctx, "cat", "run-jq.broken.json").Run().StdErr().Stream(&file)
	if err != nil {
		panic(err)
	}
	println(file.String())
```

**Comment by bobheadxi** [comment]
Stepping through a debugger shows this gets to `Wait()` and then gets stuck:

```
// Wait waits for the command to exit and waits for any copying to
// stdin or copying from stdout or stderr to complete.
//
// The command must have been started by Start.
//
// The returned error is nil if the command runs, has no problems
// copying stdin, stdout, and stderr, and exits with a zero exit
// status.
//
// If the command fails to run or doesn't complete successfully, the
// error is of type *ExitError. Other error types may be
// returned for I/O problems.
//
// If any of c.Stdin, c.Stdout or c.Stderr are not an *os.File, Wait also waits
// for the respective I/O loop copying to or from the process to complete.
//
// Wait releases any resources associated with the Cmd.
```

**Comment by bobheadxi** [comment]
This shows content:

```
	go func() {
		for {
			time.Sleep(1 * time.Second)
			b := make([]byte, 40)
			stdoutReader.Read(b)
			println(string(b))
		}
	}()
```

This hangs indefinitely: 

```go
	for {
			time.Sleep(3 * time.Second)
			b, _ := ioutil.ReadAll(stdoutReader)
			println(string(b))
		}
```

**Comment by bobheadxi** [comment]
More debugging shows we get stuck on reading from the source that the aggregator provides to `io.Copy`, which is usually an `os.Pipe`'s reader

**Comment by bobheadxi** [comment]
At some point the pipe returns 0 bytes and no error, which causes io.Copy to lock up. The last thing it reads is a partial that ends with:

```
\ncurl -L \"https:/
```

**Comment by bobheadxi** [comment]
Damn I'm kind of stumped. I've tried a few approaches, namely with https://pkg.go.dev/bufio, but I seem to be running into some kind of deadlock/weird read result regardless

**Comment by bobheadxi** [comment]
Wait `66340` is the size of the file:

```
wc -c run-jq.broken.json 
```

what the heck I am so stumped

**Comment by bobheadxi** [comment]
content size is definitely the issue, if you delete a bit of data from `run-jq.broken.json` everything works again. Still unable to find a way around this :(
