### ISSUE TITLE
idea: remove output.StdOut

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/run#27]
Discussed briefly yesterday with @michaellzc , @danieldides , @daxmc99 - this might be a pretty rare use case, how often do you _just_ get `StdOut`? Usually you would only want combined output, or just `StdErr`.

Removal would simplify the piping implementation

Also related, do we ever really only get `StdErr` outside of the error scenario, in which case it is included in the returned `error`? Maybe we could just remove both `StdOut` and `StdErr` in favour of focusing on the combined output use case?

cc @jhchabran

**Comment by michaellzc** [comment]
I don't have a use case where I just want stdout, also it's a bad idea to filter stuff based on `stdout` and `stderr` anyway...

especially when I am calling someone else binary, I just want to see everything at the same time
