### ISSUE TITLE
Cannot pass strings with spaces to Cmd

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/run#34]
For example, 

```go
run.Cmd(ctx, "gcloud", "compute", "disks", "snapshot",
		conf.CurrentInstanceDisk(), "--zone", conf.CurrentInstanceZone(),
		"--description", "mg cli driven backup",
		"--snapshot-names", snapshotName,
	).Run().StdOut().Stream(os.Stdout)
```

This will pass `mg cli driven backup` as separate commands. 

How should we tell `Cmd` to not split certain strings?

**Comment by daxmc99** [comment]
cc @bobheadxi

**Comment by bobheadxi** [comment]
You need to quote the argument @daxmc99 , we don't do implicit quoting ( https://github.com/sourcegraph/run/issues/11 )

**Comment by bobheadxi** [comment]
https://github.com/sourcegraph/run/pull/36 tries to make this clearer
