### ISSUE TITLE
jq support

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/run#4]
https://github.com/sourcegraph/run/blob/main/output.go#L34

Another thought: maybe we can just implement this as `LineFilter`? e.g.

```go
run.Cmd(...).Run().Filter(run.JQ("...")).Lines()
```

cc @jhchabran

**Comment by michaellzc** [comment]
I would love to see this happen

right now it's quite hacky to get `jq` working (we could do the filtering and selecting in go after unmarshalling it, but it's super annoying)

https://github.com/sourcegraph/deploy-sourcegraph-managed/pull/501/files#diff-19a4a3c083ebe3c7805b79dcc57f2cf2ace1d5805f78e765a051d649c263016dR117

**Comment by bobheadxi** [comment]
pure-go like this: https://github.com/sourcegraph/run/pull/12 😋
